## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/reddit_login"
  to = "http://redditroyalenodeserver-env.eba-czhqveiw.us-east-1.elasticbeanstalk.com/api/auth/reddit"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
