## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/reddit_login"
  to = "https://www.reddit-royale-server.xyz/api/auth/reddit/callback"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
