## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/reddit_login"
  to = "https://reddit-royale.herokuapp.com/api/auth/reddit"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
